const $=s=>document.querySelector(s),state={projects:[],active:null,entries:[],editing:null,pendingDelete:null};
const icons={edit:'<svg viewBox="0 0 24 24"><path d="M12 20h9M16.5 3.5l4 4L8 20l-5 1 1-5z"/></svg>',trash:'<svg viewBox="0 0 24 24"><path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/></svg>'};
async function api(path,opts={}){const headers={'X-Tech-Memory':'1',...(opts.headers||{})};if(opts.body)headers['Content-Type']='application/json';const r=await fetch(path,{credentials:'same-origin',...opts,headers});let d={};try{d=await r.json()}catch{}if(r.status===401){showLogin();throw Error('请先登录')}if(!r.ok||d.ok===false)throw Error(d.error||d.msg||'请求失败');return d}
function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden');$('#password').focus()}function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden')}
function toast(msg){const el=$('#toast');el.textContent='✓  '+msg;el.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),2200)}
function splitContent(text=''){const parts=text.split(/\n\s*\n/),title=(parts.shift()||'未命名记录').trim();return{title,body:parts.join('\n\n').trim()}}
function fmt(s){if(!s)return'';const d=new Date(s.replace(' ','T'));return Number.isNaN(d.valueOf())?s:new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function projectUrl(name,suffix=''){return'/api/projects/'+encodeURIComponent(name)+suffix}
async function loadProjects(preferred){const d=await api('/api/projects');state.projects=d.projects||[];if(preferred)state.active=state.projects.find(p=>p.name===preferred)||null;if(!state.active||!state.projects.some(p=>p.name===state.active.name))state.active=state.projects[0]||null;renderProjects();if(state.active)await loadEntries();else renderEmptyWorkspace()}
function renderProjects(){$('#projects').innerHTML=state.projects.map((p,i)=>`<button data-project="${escapeHtml(p.name)}" class="project ${state.active?.name===p.name?'active':''}"><i style="--dot:${['#cf5a3b','#406761','#8b6b3f','#6d6689'][i%4]}"></i><span>${escapeHtml(p.name)}</span><em>${p.cnt}</em></button>`).join('');document.querySelectorAll('[data-project]').forEach(b=>b.onclick=async()=>{state.active=state.projects.find(p=>p.name===b.dataset.project);renderProjects();toggleMobileProjects(false);await loadEntries()})}
async function loadEntries(){const d=await api(projectUrl(state.active.name,'/entries'));state.entries=(d.entries||[]).slice().reverse();$('#project-title').textContent=d.project;$('#project-desc').textContent=d.desc||'把已经解决的问题、做过的决定和下一步留在这里。';$('#timeline-title').textContent='项目时间线';renderEntries(state.entries)}
function renderEntries(items){$('#entry-count').textContent=items.length;$('#last-updated').textContent=items[0]?`最近更新于 ${fmt(items[0].created_at)}`:'还没有记录';const host=$('#entries');if(!items.length){host.innerHTML='<div class="empty"><b>▤</b><h3>这里还没有记录</h3><p>写下这个项目的第一条技术记忆。</p></div>';return}host.innerHTML=items.map((e,i)=>{const c=splitContent(e.content),tags=(e.tags||'').split(/[,，\s]+/).filter(Boolean);return`<article class="memory"><div class="rail"><i class="${i===0?'current':''}"></i></div><div class="card"><header><time>${escapeHtml(fmt(e.created_at))}</time><div><button data-edit="${e.id}" aria-label="编辑记录">${icons.edit}</button><button data-delete="${e.id}" class="danger" aria-label="删除记录">${icons.trash}</button></div></header><h3>${escapeHtml(c.title)}</h3>${c.body?`<p>${escapeHtml(c.body).replace(/\n/g,'<br>')}</p>`:''}<footer>${tags.map(t=>`<span>#${escapeHtml(t)}</span>`).join('')}</footer></div></article>`}).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEntry(state.entries.find(e=>e.id===+b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>askDelete('entry',state.entries.find(e=>e.id===+b.dataset.delete)))}
function renderEmptyWorkspace(){$('#project-title').textContent='还没有项目';$('#project-desc').textContent='先创建一个项目，再写下第一条技术记忆。';$('#entry-count').textContent='0';$('#entries').innerHTML='<div class="empty"><b>＋</b><h3>创建第一个项目</h3><p>项目会把不同工作中的技术记忆分开保存。</p></div>'}
function openModal(title,overline,fields,onSubmit){$('#modal-title').textContent=title;$('#modal-overline').textContent=overline;const form=$('#modal-form');form.innerHTML=fields+'<div class="form-actions"><button type="button" data-cancel>取消</button><button class="primary" type="submit">保存 <span>→</span></button></div>';form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{await onSubmit(new FormData(form));closeModal()}catch(err){toast(err.message)}finally{button.disabled=false}};form.querySelector('[data-cancel]').onclick=closeModal;$('#modal').classList.remove('hidden');setTimeout(()=>form.querySelector('input,textarea')?.focus(),30)}
function closeModal(){$('#modal').classList.add('hidden');state.editing=null}
function openEntry(entry=null){if(!state.active){toast('请先创建项目');return}state.editing=entry;const c=splitContent(entry?.content||'');openModal(entry?'修改记录':'写一条新记录',state.active.name,`<label>标题<input name="title" required maxlength="300" value="${escapeHtml(c.title==='未命名记录'?'':c.title)}" placeholder="这次解决了什么？"></label><label>正文<textarea name="body" rows="6" placeholder="记录结论、原因和重要细节…">${escapeHtml(c.body)}</textarea></label><label>标签<input name="tags" maxlength="2000" value="${escapeHtml(entry?.tags||'')}" placeholder="用逗号分隔，例如：部署, nginx"></label>`,async f=>{const content=[f.get('title').trim(),f.get('body').trim()].filter(Boolean).join('\n\n'),body=JSON.stringify({project:state.active.name,content,tags:f.get('tags').trim()});if(entry)await api('/api/entries/'+entry.id,{method:'PUT',body});else await api('/api/entries',{method:'POST',body});await loadProjects(state.active.name);toast(entry?'记录已更新':'记录已保存')})}
function openProject(project=null){openModal(project?'编辑项目':'新建项目','项目设置',`<label>项目名称<input name="name" required maxlength="120" value="${escapeHtml(project?.name||'')}" placeholder="例如：服务器维护"></label><label>项目说明<textarea name="desc" rows="4" placeholder="这个项目是做什么的？">${escapeHtml(project?.desc||'')}</textarea></label>`,async f=>{const body=JSON.stringify({name:f.get('name').trim(),desc:f.get('desc').trim()});if(project)await api(projectUrl(project.name),{method:'PUT',body});else await api('/api/projects',{method:'POST',body});await loadProjects(f.get('name').trim());toast(project?'项目已更新':'项目已创建')})}
function askDelete(type,item){state.pendingDelete={type,item};const isProject=type==='project',name=isProject?item.name:splitContent(item.content).title;$('#confirm-title').textContent=isProject?'删除整个项目？':'删除这条记录？';$('#confirm-text').textContent=isProject?`「${name}」及其中 ${item.cnt} 条记录会被永久删除。`:`「${name}」会被永久删除。`;$('#confirm').classList.remove('hidden')}
async function confirmDelete(){const p=state.pendingDelete;if(!p)return;try{if(p.type==='project')await api(projectUrl(p.item.name),{method:'DELETE'});else await api('/api/entries/'+p.item.id,{method:'DELETE'});$('#confirm').classList.add('hidden');state.pendingDelete=null;await loadProjects();toast('已永久删除')}catch(err){toast(err.message)}}
let searchTimer;async function doSearch(q){clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{if(!q.trim()){if(state.active)await loadEntries();return}try{const d=await api('/api/search?q='+encodeURIComponent(q.trim()));state.entries=d.results||[];$('#timeline-title').textContent=`“${q.trim()}” 的结果`;renderEntries(state.entries)}catch(err){toast(err.message)}},220)}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').textContent='';try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';showApp();await loadProjects()}catch(err){$('#login-error').textContent=err.message}}
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});showLogin()};$('#new-entry').onclick=()=>openEntry();$('#mobile-add').onclick=()=>openEntry();$('#add-project').onclick=()=>openProject();$('#edit-project').onclick=()=>{toggleMenu(false);if(state.active)openProject(state.active)};$('#delete-project').onclick=()=>{toggleMenu(false);if(state.active)askDelete('project',state.active)};$('#project-menu-button').onclick=()=>toggleMenu($('#project-menu').classList.contains('hidden'));function toggleMenu(show){$('#project-menu').classList.toggle('hidden',!show);$('#project-menu-button').setAttribute('aria-expanded',String(show))}function toggleMobileProjects(show){const sidebar=$('.sidebar'),shell=$('.shell'),button=$('#mobile-projects');sidebar.classList.toggle('open',show);shell.classList.toggle('projects-open',show);button.setAttribute('aria-expanded',String(show))}$('#mobile-projects').onclick=e=>{e.stopPropagation();toggleMobileProjects(!$('.sidebar').classList.contains('open'))};$('#modal-close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#confirm-cancel').onclick=()=>$('#confirm').classList.add('hidden');$('#confirm-delete').onclick=confirmDelete;$('#search-input').oninput=e=>doSearch(e.target.value);$('#mobile-search').onclick=()=>{$('#search-input').focus();window.scrollTo({top:0,behavior:'smooth'})};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search-input').focus()}if(e.key==='Escape'){closeModal();toggleMenu(false);toggleMobileProjects(false)}});document.addEventListener('click',e=>{if(!e.target.closest('.project-menu-wrap'))toggleMenu(false);if($('.sidebar').classList.contains('open')&&!e.target.closest('.sidebar'))toggleMobileProjects(false)});
(async()=>{try{const s=await api('/api/session');if(s.authenticated){showApp();await loadProjects()}else showLogin()}catch{showLogin()}})();
